version: '3'
services:
  # Spring Boot Application
  springbootapp:
    image: simplesns:latest
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
      - redis
    networks:
      - backend
    container_name: springbootapp

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    container_name: postgres

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
    container_name: redis

networks:
  backend:

volumes:
  postgres_data:
